version: '3.8'

services:
  db:
    image: postgres:15
    container_name: health_care_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: munke
      POSTGRES_PASSWORD: health_care_app
      POSTGRES_DB: health_care
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
